### ISSUE TITLE
Fatal Exception: android.os.FileUriExposedException

### ISSUE THREAD

**Issue by maverick-2013** [kroegerama/bottomsheet-imagepicker#13]
Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/IMG_20200117_132719_5474483360980881045.jpg exposed beyond app through ClipData.Item.getUri()
       at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
       at android.net.Uri.checkFileUriExposed(Uri.java:2371)
       at android.content.ClipData.prepareToLeaveProcess(ClipData.java:963)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:10252)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:10237)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
       at android.app.Activity.startActivityForResult(Activity.java:4651)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
       at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
       at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:796)
       at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
       at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1206)
       at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1194)
       at com.kroegerama.imgpicker.BottomSheetImagePicker.launchCamera(BottomSheetImagePicker.kt:243)
       at com.kroegerama.imgpicker.BottomSheetImagePicker.access$launchCamera(BottomSheetImagePicker.kt:39)
       at com.kroegerama.imgpicker.BottomSheetImagePicker$onViewCreated$3.onClick(BottomSheetImagePicker.kt:131)
       at android.view.View.performClick(View.java:6615)
       at android.view.View.performClickInternal(View.java:6592)
       at android.view.View.access$3100(View.java:786)
       at android.view.View$PerformClick.run(View.java:25951)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6815)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by kroegerama** [comment]
Did you follow [Step 1](https://github.com/kroegerama/bottomsheet-imagepicker#step-1-create-your-own-fileprovider)?

**Comment by maverick-2013** [comment]
@kroegerama yes

**Comment by saraelmoghazy** [comment]
same issue with me .. but i added these lines to lauchCamera() function 
 intent.putExtra(MediaStore.EXTRA_OUTPUT, photoUri)

and these lines to getPhotoUri() in case create empty file
FileProvider.getUriForFile(
                context!!,
                context!!.applicationContext.packageName + ".provider",
                image
            )
and its working 

don't forget to create CustomFileProvider class extends FileProvider
